spring:
  application:
    name: cobee server

  datasource:
    url: jdbc:postgresql://localhost:5432/cobee
    username: root
    password: cobeeMate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

kakao:
  client_id: ${KAKAO_CLIENT_ID}
  redirect_uri: ${KAKAO_REDIRECT_URI}

jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: 3600000
